import{World,Entity,Weapon,GameSimulation,clamp}from'./core.js';
const MAP=[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,0,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,0,0,0,1,0,0,1,0,0,1,0,0,0,1],[1,0,1,0,1,0,0,0,0,0,1,0,1,0,1],[1,0,1,0,0,0,1,1,1,0,0,0,1,0,1],[1,0,0,0,1,0,0,0,0,0,1,0,0,0,1],[1,1,0,1,1,0,1,0,1,0,1,1,0,1,1],[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1],[1,0,1,1,0,0,0,0,0,0,0,1,1,0,1],[1,0,0,0,0,1,0,1,0,1,0,0,0,0,1],[1,0,0,0,0,0,0,1,0,0,0,0,0,0,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]];
const CLASSES={pulse:{name:'Pulse AR',damage:28,rpm:720,magazine:30},marksman:{name:'Vektor Semi',damage:48,rpm:360,magazine:18},burst:{name:'Triad Burst',damage:34,rpm:600,magazine:24}};
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),world=new World(MAP),sim=new GameSimulation({world,seed:1337}),player=sim.add(new Entity({id:'YOU',x:2.5,y:2.5})),bots=[sim.add(new Entity({id:'BOT-A',x:12.5,y:9.5,angle:Math.PI})),sim.add(new Entity({id:'BOT-B',x:12.5,y:2.5,angle:Math.PI}))];
let selected='pulse',weapon=makeWeapon(selected),running=false,paused=false,nav=false,collision=false,last=performance.now();const keys=new Set,botWeapons=new Map(bots.map((b,i)=>[b.id,makeWeapon(i?'marksman':'pulse')]));
function makeWeapon(id){const c=CLASSES[id];return new Weapon({id,damage:c.damage,rpm:c.rpm,magazine:c.magazine})}function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px'}function show(id,v=true){document.querySelector(id).classList.toggle('hidden',!v)}function status(s){document.querySelector('#status').textContent=s}
addEventListener('resize',resize);resize();for(const c of document.querySelectorAll('[data-class]'))c.onclick=()=>{selected=c.dataset.class;for(const x of document.querySelectorAll('[data-class]'))x.classList.toggle('selected',x===c);document.querySelector('#equip').disabled=false};document.querySelector('#start').onclick=()=>show('#classMenu');document.querySelector('#equip').onclick=()=>{weapon=makeWeapon(selected);show('#classMenu',false);running=true;canvas.requestPointerLock?.()};document.querySelector('#resume').onclick=()=>{paused=false;show('#pause',false);canvas.requestPointerLock?.()};document.querySelector('#respawn').onclick=()=>sim.respawn(player);document.querySelector('#classAgain').onclick=()=>show('#classMenu');document.querySelector('#nav').onclick=()=>nav=!nav;document.querySelector('#collision').onclick=()=>collision=!collision;
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Escape'&&running){paused=true;show('#pause')}if(e.code==='KeyR')weapon.ammo=weapon.magazine});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!paused)player.angle+=e.movementX*.0024});addEventListener('mousedown',e=>{if(e.button===0&&running&&!paused)sim.shoot(player,weapon)});
function update(dt){if(!running||paused)return;const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),s=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);sim.move(player,f,s,dt);sim.tick(dt);for(const b of bots){if(!b.alive){if(sim.time%3<dt)sim.respawn(b);continue}sim.botThink(b,player,botWeapons.get(b.id),dt);if(botWeapons.get(b.id).ammo===0)botWeapons.set(b.id,makeWeapon('pulse'))}status(player.alive?`${CLASSES[selected].name} • ${weapon.ammo}/${weapon.magazine} • HP ${player.health}`:'ELIMINATED — click Respawn');document.querySelector('#score').innerHTML=[...sim.entities.values()].sort((a,b)=>b.kills-a.kills).map(e=>`<tr><td>${e.id}</td><td>${e.kills}</td><td>${e.deaths}</td></tr>`).join('')}
function render(){const W=canvas.width,H=canvas.height;ctx.fillStyle='#08131f';ctx.fillRect(0,0,W,H);ctx.fillStyle='#142c42';ctx.fillRect(0,H/2,W,H/2);const rays=Math.max(220,Math.floor(W/3)),fov=Math.PI/2.9;for(let i=0;i<rays;i++){const a=player.angle-fov/2+i/(rays-1)*fov,hit=world.raycast(player,a,20,.035),d=hit.distance*Math.cos(a-player.angle),wallH=clamp(H/(d+.01),0,H*1.8),shade=clamp(220-d*14,40,210),x=i*W/rays;ctx.fillStyle=`rgb(${shade*.35},${shade*.75},${shade})`;ctx.fillRect(x,H/2-wallH/2,W/rays+1,wallH)}for(const e of sim.entities.values()){if(e.id===player.id||!e.alive)continue;const dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy);let rel=Math.atan2(dy,dx)-player.angle;rel=Math.atan2(Math.sin(rel),Math.cos(rel));if(Math.abs(rel)<fov/2&&d<12&&world.raycast(player,player.angle+rel,d,.04).distance+.15>=d){const sx=(rel/fov+.5)*W,size=H/(d+.5)*.45;ctx.fillStyle='#ff5d73';ctx.fillRect(sx-size/2,H/2-size/2,size,size)}}if(nav||collision)drawMap();ctx.strokeStyle='#fff';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();ctx.moveTo(W/2-10,H/2);ctx.lineTo(W/2+10,H/2);ctx.moveTo(W/2,H/2-10);ctx.lineTo(W/2,H/2+10);ctx.stroke()}
function drawMap(){const sc=12*devicePixelRatio,ox=16*devicePixelRatio,oy=80*devicePixelRatio;ctx.globalAlpha=.85;for(let y=0;y<MAP.length;y++)for(let x=0;x<MAP[y].length;x++){ctx.fillStyle=MAP[y][x]?'#28445e':nav?'#42f5c5':'#0d1c29';ctx.fillRect(ox+x*sc,oy+y*sc,sc-1,sc-1)}for(const e of sim.entities.values()){ctx.fillStyle=e.id==='YOU'?'#fff':'#ff5d73';ctx.beginPath();ctx.arc(ox+e.x*sc,oy+e.y*sc,3*devicePixelRatio,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function loop(now){const dt=Math.min(.05,(now-last)/1e3);last=now;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
